Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NEPATechDotnetCoreMVC.Data;
using NEPATechDotnetCoreMVC.ViewModel;

namespace NEPATechDotnetCoreMVC.Controllers
{
    public class ContactUsController : Controller
    {
        [BindProperty]
        public string fname { get; set; }
        [BindProperty]
        public string lname { get; set; }
        [BindProperty]
        public string email { get; set; }
        [BindProperty]
        public string complaint { get; set; }

        private ContactViewModel contactViewModel = new ContactViewModel();
        private NEPATechDbContext _context;

        public ContactUsController(NEPATechDbContext _context)
        {
            contactViewModel.isComplaintSent = false;
            this._context = _context;
        }

        public IActionResult Index()
        {
            if(Request.Method == "POST")
            {
                var ContactLogs = _context.ContactLogs;
                ContactLogs.Add(new Models.ContactLog.ContactLog
                {
                    FName = fname,
                    LName = lname,
                    Email = email,
                    Message = complaint
                });

                _context.SaveChanges();
                contactViewModel.isComplaintSent = true;
            }
            return View(contactViewModel);
        }
        public IActionResult eventsRedirect()
        {
            return Redirect("https://www.meetup.com/NEPATech/events/past/");
        }
    }
}

Views/Shared/_HeaderPartial.cshtml
@{
}

<!-- Header -->
<header id="header">
    <a class="logo" id="formatTitleHeader" asp-area="" asp-controller="Home" asp-action="Index">@ViewData["Title"]</a>
    <ul class="icons">
        <li><a href="https://www.meetup.com/NEPA-js/" target="_blank" rel="noopener noreferrer" class="icon fa-meetup"><span class="label">Meetup</span></a></li>
        <li><a href="https://www.facebook.com/NEPATechGroup/" target="_blank" rel="noopener noreferrer" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
        <li><a href="https://www.reddit.com/r/NEPATech/" class="icon fa-reddit-alien"><span class="label">Reddit</span></a></li>
        @if (!User.Identity.IsAuthenticated)
        {
            <li class="login">@Html.ActionLink("Login", "Login", "Account", null, new { @class = " " })</li>
            <li class="login">@Html.ActionLink("Register", "Register", "Account", null, new { @class = "last" })</li>
        }
        else
        {
            <li class="login">@Html.ActionLink("Logout", "Logout", "Account", null, new { @class = "btn special fit" })</li>

        }
    </ul>
</header>

Views/Shared/_HeaderPartialNoIcons.cshtml
@{
}

<!-- Header -->
<header id="header">
    <a class="logo" id="formatTitleHeader" asp-area="" asp-controller="Home" asp-action="Index">@ViewData["Title"]</a>
    <ul class="icons">
        @if (!User.Identity.IsAuthenticated)
        {
            @if (ViewData["Title"].Equals("Login"))
            {
                <li class="login">@Html.ActionLink("Register", "Register", "Account", null, new { @class = "last" })</li>
            }
            else{
                <li class="login">@Html.ActionLink("Login", "Login", "Account", null, new { @class = " " })</li>
            }
        }
        else
        {
            <li class="login">@Html.ActionLink("Logout", "Logout", "Account", null, new { @class = "btn special fit" })</li>
        }
    </ul>
</header>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using NEPATechDotnetCoreMVC.ViewModel.AccountViewModels;

@inject SignInManager<ApplicationUser> _signInManager;
@inject UserManager<ApplicationUser> _userManager;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/css/styles.css" />
    <link rel="stylesheet" href="~/css/font-awesome.css" />
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>

</head>
<body>

    <!-- Wrapper -->
    <div id="wrapper">

        <!-- Main -->
        <div id="main" class="container-fluid">
            @RenderBody()
        </div>

        <!-- Sidebar -->
        <div id="sidebar">
            <div class="inner">
                <!-- Menu -->
                <nav id="menu">

                    
                    <header class="major">
                        <h2>Menu</h2>
                    </header>
                    <ul>
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Homepage</a></li>
                        <li><a asp-area="" asp-controller="ContactUs" asp-action="eventsRedirect" target="_blank">Events</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Members">Members</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a></li>
                    </ul>
                </nav>
            </div>
            
        </div>
    </div>


    <!-- Scripts -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="http://code.jquery.com/ui/1.8.23/jquery-ui.min.js" type="text/javascript"></script>
    <script src="~/lib/skel.min.js"></script>
    <script src="~/lib/util.js"></script>
    <script src="~/lib/main.js"></script>
    <script type="text/javascript">
    </script>
</body>
</html>

Views/Shared/_LoginPartialView.cshtml
@model NEPATechDotnetCoreMVC.ViewModel.AccountViewModels.LoginViewModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col"></div>
        <div class="col"></div>
        <div class="col"></div>
        <div class="col"></div>
        <div class="col-xs-offset-1 col-xs-6 col-sm-6 col-md-6">
            <div class="loginMenu">
                @Html.Partial("_HeaderPartialNoIcons", null)
                <div class="loginWrapper">
                    <div class="loginMenuContent">
                        <div asp-validation-summary="All"></div>
                        <form asp-controller="Account" asp-action="Login">
                            @Html.Hidden("ReturnUrl", Context.Request.Path)
                            <fieldset>
                                <div class="form-group">
                                    <label asp-for="Email"></label>
                                    <input asp-for="Email" />
                                    <span asp-validation-for="Email"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Password"></label>
                                    <input asp-for="Password" />
                                    <span asp-validation-for="Password"></span>

                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" asp-for="RememberMe">
                                    <label class="form-check-label" asp-for="RememberMe">
                                        Remember Me
                                    </label>
                                </div>
                                <br />
                                <input runat="server" type="submit" name="loginSubmit" value="Login" class="special fit" />
                                @*@Html.ActionLink("Create new account", "Register", "Account", null, new { @class = "btn special fit", @onclick = "toggleRegistrationOverlay(true); return false;", @id="RegisterBtn" })*@

                            </fieldset>
                        </form>
                    </div>
                </div>
                <div class="loginFooter">
                    @Html.ActionLink("Forgot your password?", "ForgotPassword", "Account", null, new { @class = "btn special fit" })
                </div>
            </div>
        </div>
        <div class="col"></div>
        <div class="col"></div>
        <div class="col"></div>
        <div class="col"></div>
        <div class="col"></div>
    </div>
</div>

Views/Shared/_RegisterPartialView.cshtml
@model NEPATechDotnetCoreMVC.ViewModel.AccountViewModels.RegisterViewModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@



@*<div id="registrationOverlay">
        <div class="container-fluid">
            <div class="row">
                <div class="col">
                    <div class="registrationInner">
                        @*<input type="button" class="button special small smallExitButton" value="x" onclick="toggleRegistrationOverlay(false)" />
                        <div class="registrationHeader">
                            <h2 class="logo">Registration</h2>
                            <p id="registrationError" class="text-danger">*Passwords do not match!</p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>*@


<div class="container">
    <div class="row align-items-center">
        <div class="col"></div>
        <div class="col"></div>
        <div class="col"></div>
        <div class="col"></div>
        <div class="col"></div>
        <div class="col-xs-offset-1 col-xs-6 col-sm-6 col-md-6">
            <div class="registerMenu">
                @Html.Partial("_HeaderPartialNoIcons", null)
                <div class="registerMenuContent">
                    <div asp-validation-summary="All"></div>
                    <form asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post" autocomplete="off">

                        @Html.Hidden("ReturnUrl", Context.Request.Path)
                        <div asp-validation-summary="All"></div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col">
                                    <label asp-for="FirstName"></label>
                                    <input asp-for="FirstName" class="form-control" />
                                    <span asp-validation-for="FirstName"></span>
                                </div>
                                <div class="col">
                                    <label asp-for="LastName"></label>
                                    <input asp-for="LastName" class="form-control" />
                                    <span asp-validation-for="LastName"></span>
                                </div>
                            </div>


                        </div>
                        <div class="form-group">
                            <label asp-for="Email"></label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Password"></label>
                            <input asp-for="Password" class="form-control" />
                            <span asp-validation-for="Password"></span>
                            <label asp-for="ConfirmPassword"></label>
                            <input asp-for="ConfirmPassword" class="form-control" />
                            <span asp-validation-for="ConfirmPassword"></span>

                        </div>
                        <div class="registerFooter">
                            <input type="submit" class="special fit" value="Register" />
                        </div>

                    </form>
                </div>
                <div class="loginFooter">
                </div>
            </div>
        </div>
        <div class="col"></div>
        <div class="col"></div>
        <div class="col"></div>
        <div class="col"></div>
        <div class="col"></div>
    </div>
</div>